name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.7
      uses: actions/setup-go@v2 
      with:
        go-version: 1.14.7

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5

    - name: Test
      run: make test

    - name: Build
      run: make build
