name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Looks like this is your first issue. Welcome to the community! :wave:'
        pr-message: 'Looks like you just opened your first PR. :clap: This is awesome, thanks and keep up!'
